name: oaivenv
channels:
  - default
  - conda-forge
dependencies:
  - tiktoken 
  - langchain
  - openai
  - pip  
  - pip:
    - azure-ai-projects
    - azure-identity
    - azure-ai-agents
    - azure-search-documents
    - azure-data-tables
    - azure-storage-blob
    - semantic-text-splitter
    - tokenizers
    - pydantic_settings
  