[app]
name = "demo-openai"
host = "0.0.0.0"
port = 8000
log_level = "INFO"

[database]
host = "localhost"
port = 5432
name = "demo_db"

[features]
enable_cache = true

[azure_openai]
endpoint = ""
key = ""
version = ""
embedded_model = ""

[azure_ai_search]
search = ""
index_name = ""
key = ""

