[app]
name = "demo-openai"
host = "0.0.0.0"
port = 8000
log_level = "INFO"

[database]
host = "localhost"
port = 5432
name = "demo_db"

[features]
enable_cache = true

[azure_openai]
endpoint = ""
key = ""
version = ""
embedded_model = ""
model_deployment_name = ""

[azure_ai_search]
search = ""
index_name = ""
key = ""

[azure_ai_foundry]
endpoint = ""
agent_id = ""

[azure_storage_account]
table_service_url  = ""
table_name = ""


