name: cvenv
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - metaflow
  - ipykernel
  - langchain
  - langchain-core
  - langchain-huggingface
  - pip  
  - pip:
      - langchain-milvus
