# Deploy Milvus in standalone mode
cluster:
  enabled: false

# Use Azure Blob Storage instead of MinIO
common:
  deployMode: standalone
  storageType: remote
  storage: azure
  bucketName: milvusfiles
  azure:
    accountName: stpetshopmilvus
    containerName: milvusfiles
  minio:
    enabled: false
    endpoint: ""

# Disable MinIO completely
minio:
  enabled: false
  endpoint: ""
  tls:
    enabled: false

labels:
  azure.workload.identity/use: "true"

image:
  all:
    repository: milvusdb/milvus
    tag: v2.6.3 
    pullPolicy: IfNotPresent

streaming:
  enabled: false

serviceAccount:
  create: true
  name: milvus-sa
  annotations:
    azure.workload.identity/client-id: "dada9585-daf7-48f4-aca4-6e4e5530f037"

externalS3:
  enabled: true
  host: "core.windows.net"
  port: 443
  rootPath: milvus #release name
  useSSL: true
  useIAM: true
  bucketName: milvusfiles #container name
  cloudProvider: azure
  accessKey: "stpetshopmilvus" # the storage account name
  secretKey: "" # No storage account key


# Milvus standalone pod configuration
standalone:
  serviceAccountName: milvus-sa
  extraArgs:
    - "run"
    - "standalone"
  nodeSelector:
    kubernetes.io/arch: amd64
  
  livenessProbe:
    enabled: false

#remove and test functionality
  extraEnv:
    - name: DEPLOY_MODE
      value: "standalone"
    - name: STORAGE_TYPE
      value: "azure"
    - name: AZURE_STORAGE_ACCOUNT
      value: "stpetshopmilvus"
    - name: AZURE_STORAGE_CONTAINER
      value: "milvusfiles"
    - name: AZURE_STORAGE_ENDPOINT
      value: "stpetshopmilvus.blob.core.windows.net"
    - name: MINIO_USE_AZURE
      value: "true" 
  
  #remove and test functionality
  command: ["/milvus/bin/milvus"]
  args: ["run", "standalone"]

  persistence:
    enabled: true
    size: 20Gi #remove
    storageClass: default


# etcd configurationI have
etcd:
  replicaCount: 1
  architecture: amd64
  persistence:
    enabled: true
    size: 10Gi
    storageClass: managed-premium

# Disable Pulsar (not needed for standalone)
pulsar:
  enabled: false
pulsarv3:
  enabled: false

# Disable all distributed components
mixCoordinator:
  enabled: false
queryNode:
  enabled: false
dataNode:
  enabled: false
indexNode:
  enabled: false
queryCoord:
  enabled: false
dataCoord:
  enabled: false
indexCoord:
  enabled: false
rootCoord:
  enabled: false

# Expose Milvus via LoadBalancer for external access
service:
  type: LoadBalancer
  port: 19530