# Deploy Milvus in standalone mode
cluster:
  enabled: false

# Use Azure Blob Storage instead of MinIO
common:
  deployMode: standalone
  storageType: remote
  storage: azure

# Disable MinIO completely
minio:
  enabled: false
  endpoint: ""
  tls:
    enabled: false

labels:
  azure.workload.identity/use: "true"

image:
  all:
    repository: milvusdb/milvus
    tag: v2.6.3 
    pullPolicy: IfNotPresent

streaming:
  enabled: false

serviceAccount:
  create: true
  name: milvus-sa
  annotations:
    azure.workload.identity/client-id: "c9fd7803-1ab9-4b3e-af76-7d12ad5f0e91"

externalS3:
  enabled: true
  host: "core.windows.net"
  port: 443
  rootPath: milvus #release name
  useSSL: true
  useIAM: true
  bucketName: milvusfiles01 #container name
  cloudProvider: azure
  accessKey: "stpetshopmilvus01" # the storage account name
  secretKey: "" # No storage account key


# Milvus standalone pod configuration
standalone:
  serviceAccountName: milvus-sa

  nodeSelector:
    kubernetes.io/arch: amd64
  
  livenessProbe:
    enabled: false

  persistence:
    enabled: true
    size: 20Gi #remove
    storageClass: default

# etcd configurationI have
etcd:
  replicaCount: 1
  architecture: amd64
  persistence:
    enabled: true
    size: 10Gi
    storageClass: managed-premium

# Disable Pulsar (not needed for standalone)
pulsar:
  enabled: false
pulsarv3:
  enabled: false

# Disable all distributed components
queryNode:
  enabled: false
dataNode:
  enabled: false
indexNode:
  enabled: false
queryCoord:
  enabled: false
dataCoord:
  enabled: false
indexCoord:
  enabled: false
rootCoord:
  enabled: false

# Expose Milvus via LoadBalancer for external access
service:
  type: LoadBalancer
  port: 19530